# name: flutter_application_1

# dependencies:
#   flutter:
#     sdk: flutter
#     assets: - assets/images/Jelantik_Logo.png
#   provider: ^6.0.0
#   http: ^0.14.0
#   shared_preferences: ^2.0.15
#   flutter_svg: ^1.1.1



name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Tambahkan package ini untuk indikator halaman (titik-titik)
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  # Pastikan Anda sudah mendaftarkan folder aset seperti ini
  assets:
    - assets/images/
    - assets/images/Subtract.png
    - assets/images/Subtract (1).png
    - assets/images/Ellipse 245.png
    - assets/images/Mask Group.png
    - assets/images/lightning-bolt.png
    - assets/images/Line 1.png
     - assets/images/Next.png

fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
